FROM {{ .nginxImage }}

COPY nginx.conf /etc/nginx/nginx.conf
COPY conf.d /etc/nginx/conf.d
COPY public /usr/share/nginx/html

RUN cp /etc/nginx/conf.d/prod.conf /etc/nginx/conf.d/active.conf \
	&& rm -f /etc/nginx/conf.d/default.conf

EXPOSE {{ .containerPort }}

CMD ["nginx", "-g", "daemon off;"]